version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    environment:
      discovery.type: "single-node"
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
  benthos:
    image: jeffail/benthos
    depends_on:
      - elasticsearch
    environment:
      INPUT_TYPE: "kafka_balanced"
      INPUT_KAFKA_BALANCED_ADDRESSES: "localhost:29092"
      INPUT_KAFKA_BALANCED_TOPICS: "kafka-topic"
      OUTPUT_TYPE: "elasticsearch"
      OUTPUT_ELASTICSEARCH_URLS: "http://elasticsearch:9200"
